# syntax=edrevo/dockerfile-plus

FROM outeredge/edge-docker-magento:1.9.4.4 AS magento1
FROM outeredge/edge-docker-php:5.6

ENV APPLICATION_ENV=dev \
    MAGE_IS_DEVELOPER_MODE=true

INCLUDE+ Dockerfile.common

COPY --from=magento1 /etc/nginx/magento_security.conf /etc/nginx/
COPY --from=magento1 /templates/nginx-magento.conf.j2 /templates/nginx-magento1.conf.j2