# syntax=edrevo/dockerfile-plus

FROM outeredge/edge-docker-magento:2.3.5-p2 AS magento
FROM outeredge/edge-docker-php:7.3

INCLUDE+ Dockerfile.common

COPY --from=magento \
        /templates/magento.conf.j2 \
        /templates/nginx-magento.conf.j2 \
    /templates/
