[program:sql-proxy]
command=cloud-sql-proxy
autostart={% if ENABLE_SQL_PROXY == 'On' %}true{% else %}false{% endif %}
user=edge
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
